=== juanro49/DAM/DAM1/LM/Ejercicios XML/305b.dtd
<!ELEMENT biblioteca (libro+)>
  <!ELEMENT libro (titulo,autor,fechapublicacion)>
  <!ELEMENT titulo (#PCDATA)>
  <!ELEMENT autor (#PCDATA)>
    <!ATTLIST autor fechanacimiento CDATA #IMPLIED>
  <!ELEMENT fechapublicacion EMPTY>
    <!ATTLIST fechapublicacion aÃ±o NMTOKEN #REQUIRED>

=== juanro49/DAM/DAM1/LM/Ejercicios XML/305b.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "305b.dtd">
<biblioteca>
<libro>
  <titulo>La vida esta en otra parte</titulo>
  <autor>Milan Kundera</autor>
  <fechapublicacion año="1973"/>
</libro>
<libro>
  <titulo>Pantaleón y las visitadoras</titulo>
  <autor fechanacimiento="28/03/1936">Mario Vargas Llosa</autor>
  <fechapublicacion año="1973"/>
</libro>
<libro>
  <titulo>Conversación en la catedral</titulo>
  <autor fechanacimiento="28/03/1936">Mario Vargas Llosa</autor>
  <fechapublicacion año="1969"/>
</libro>
</biblioteca>
