=== juanro49/DAM/DAM1/LM/Ejercicios XML/305c.dtd
<!ELEMENT cd (artista,titulocd,fechacrea,genero,cancion+)>
  <!ELEMENT artista (nombre,fechanaci,lugarnaci)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT fechanaci (#PCDATA)>
    <!ELEMENT lugarnaci (#PCDATA)>
  <!ELEMENT titulocd (#PCDATA)>
  <!ELEMENT fechacrea (#PCDATA)>
  <!ELEMENT genero (#PCDATA)>
  <!ELEMENT cancion (titulo,duracion)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT duracion (#PCDATA)>
      <!ATTLIST duracion tiempo NMTOKEN #REQUIRED>

=== juanro49/DAM/DAM1/LM/Ejercicios XML/305c.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cd SYSTEM "305c.dtd">
<cd>
    <artista>
      <nombre>Concha Piquer</nombre>
      <fechanaci>08/12/1906</fechanaci>
      <lugarnaci>Valencia</lugarnaci>
  </artista>
  <titulocd>Grandes Éxitos</titulocd>
  <fechacrea>01/01/2014</fechacrea>
  <genero>Canción Española</genero>
  <cancion>
      <titulo>Ojos verdes</titulo>
      <duracion tiempo="minutos">2.5</duracion>
  </cancion>
  <cancion>
      <titulo>Tatuaje</titulo>
      <duracion tiempo="minutos">2.9</duracion>
  </cancion>
  <cancion>
      <titulo>Suspiros de España</titulo>
      <duracion tiempo="minutos">3.2</duracion>
  </cancion>
</cd>
