=== juanro49/DAM/DAM1/LM/Ejercicios XML/305d.dtd
<!ELEMENT hoteles (hotel+)>
<!ELEMENT hotel (nombre, direccion, ciudad, pais, estrellas, descripcion, habitaciones)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT direccion (calle, numero)>
    <!ELEMENT calle (#PCDATA)>
    <!ELEMENT numero (#PCDATA)>
  <!ELEMENT ciudad (#PCDATA)>
  <!ELEMENT pais (#PCDATA)>
  <!ELEMENT estrellas (#PCDATA)>
  <!ELEMENT descripcion (parrafo+)>
    <!ELEMENT parrafo (#PCDATA)>
  <!ELEMENT habitaciones (individuales, dobles, triples, suties)>
    <!ELEMENT individuales (#PCDATA)>
    <!ELEMENT dobles (#PCDATA)>
    <!ELEMENT triples (#PCDATA)>
    <!ELEMENT suties (#PCDATA)>

=== juanro49/DAM/DAM1/LM/Ejercicios XML/305d.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hoteles SYSTEM "305d.dtd">
<hoteles>
    <hotel>
      <nombre>Senator</nombre>
      <direccion>
        <calle>Alcalá</calle>
        <numero>10</numero>
      </direccion>
      <ciudad>Madrid</ciudad>
      <pais>España</pais>
      <estrellas>5</estrellas>
      <descripcion>
        <parrafo>Hotel de lujo</parrafo>
        <parrafo>Situado en el centro de Madrid</parrafo>
      </descripcion>
      <habitaciones>
        <individuales>20</individuales>
        <dobles>30</dobles>
        <triples>15</triples>
        <suties>8</suties>
      </habitaciones>
    </hotel>
    <hotel>
      <nombre>Extremadura</nombre>
      <direccion>
        <calle>Ruta de la Plata</calle>
        <numero>1</numero>
      </direccion>
      <ciudad>Cáceres</ciudad>
      <pais>España</pais>
      <estrellas>4</estrellas>
      <descripcion>
        <parrafo>Hotel funcional</parrafo>
        <parrafo>Situado a la entrada de Cáceres</parrafo>
      </descripcion>
      <habitaciones>
        <individuales>10</individuales>
        <dobles>40</dobles>
        <triples>5</triples>
        <suties>16</suties>
      </habitaciones>
    </hotel>
  </hoteles>
