=== juanro49/DAM/DAM1/LM/Ejercicios XML/306b.dtd
<!ELEMENT persona (nombre, nacimiento?, dirección+, sexo?,nombre, nacimiento?, dirección+, sexo?)>
  <!ELEMENT nombre (#PCDATA)>
    <!ATTLIST nombre dni ID #REQUIRED>
  <!ELEMENT nacimiento EMPTY>
    <!ATTLIST nacimiento día NMTOKEN #REQUIRED
                                          mes NMTOKEN #REQUIRED
                                          año NMTOKEN #REQUIRED>
  <!ELEMENT dirección EMPTY>
    <!ATTLIST dirección calle NMTOKENS #REQUIRED>
    <!ATTLIST dirección población NMTOKEN #REQUIRED>
    <!ATTLIST dirección provincia NMTOKEN #REQUIRED >
  <!ELEMENT sexo (varón | hembra)>
    <!ELEMENT varón EMPTY>
    <!ELEMENT hembra EMPTY>

=== juanro49/DAM/DAM1/LM/Ejercicios XML/306b.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE persona SYSTEM "306b.dtd">

<persona>
  <nombre dni="D00000000A">Persona 1</nombre>
  <nacimiento día="1" mes="1" año="0"/>
  <dirección calle="calle 1" población="pueblolandia" provincia="independiente"/>
  <nombre dni="D99999999Z">Persona 2</nombre>
  <dirección calle="mi calle" población="pueblolandia" provincia="independiente"/>
  <dirección calle="calle 2" población="pueblo" provincia="melilla"/>
  <sexo>
    <hembra/>
  </sexo>
</persona>
