<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE agenda [ 
	<!ELEMENT agenda (contacto*)> 
	<!ELEMENT contacto (nombre, telefonoFijo, telefonoMovil*, telefonoFijo*)> 
	<!ELEMENT nombre (#PCDATA)> 
	<!ELEMENT telefonoFijo (#PCDATA)>
  <!ELEMENT telefonoMovil (#PCDATA)> 
]> 
 
<agenda> 
	<contacto> 
	   <nombre>Ayuntamiento</nombre> 
	   <telefonoFijo>010</telefonoFijo> 
	</contacto> 
	<contacto> 
	   <nombre>Emergencias</nombre> 
	   <telefonoFijo>112 (Unión Europea)</telefonoFijo> 
	   <telefonoMovil>Desconocido</telefonoMovil> 
	   <telefonoFijo>911 (Estados Unidos)</telefonoFijo> 
	</contacto>
</agenda>